services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: Satish@@1303
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: backend-app:latest
    container_name: backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Satish@@1303
    ports:
      - "8080:8080"
    restart: on-failure

  frontend:
    image: frontend-app:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: on-failure

volumes:
  mysql_data:
